default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: check-valid-kai
        name: JSON Validation Kai
        entry: mibigger/helper/check_valid.py
        language: python
        additional_dependencies: ["jsonschema==4.17.3"]
        files: \.json$
        exclude: (ripp_subclasses.json|ripp_tailoring.json)